openapi: 3.0.0
info:
  title: 'Serverless TypeScript Boilerplate'
  description: "Change this description."
  version: 1.0.0

paths:
  /hello:
    $ref: './functions/hello.yml#/paths'
  /users:
    $ref: './functions/users.yml#/paths'

components:
  schemas:
    User:
      properties:
        name:
          type: string
          example: John
        age:
          type: integer
          format: int64
          example: 198772
      type: object
